name: Build and Deploy to OpenShift

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Check for target directory and files
        run: |
          ls -l target
          ls -l target/nationalparks.jar

      - name: Build Docker Image with Tags
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: |
          docker build -t nationalparks:latest -t nationalparks:${GITHUB_SHA} .
