name: OpenShift Deployment and Prisma Scan

on:
  push: 
    branches: [ master ]

jobs:
  build-and-deploy:
    name: Build, Push, Deploy to OpenShift, and Scan
    runs-on: ubuntu-22.04
    environment: development

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn clean package  # Or use ./gradlew build for Gradle

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and Push Docker Image
      id: build-and-push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        tags: |
          ghcr.io/${{ github.repository_owner }}/nationalparks:latest
          ghcr.io/${{ github.repository_owner }}/nationalparks:${{ github.sha }}
        push: true
    - name: Prisma Cloud Scan
      uses: PaloAltoNetworks/prisma-cloud-scan@v1
      with:
        pcc_console_url: ${{ secrets.PCC_CONSOLE_URL }}
        pcc_user: ${{ secrets.PCC_USER }}
        pcc_pass: ${{ secrets.PCC_PASS }}
        image_name: ${{ env.IMAGE_REGISTRY }}/${{ env.APP_NAME }}:latest
